
package com.nttdata.sf.partner;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * Sforce SOAP API
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SforceService", targetNamespace = "urn:partner.soap.sforce.com", wsdlLocation = "file:/C:/dev-workspace/ToolingAPI/apex-analyser/src/main/java/sf_cn_partner.wsdl")
public class SforceService
    extends Service
{

    private final static URL SFORCESERVICE_WSDL_LOCATION;
    private final static WebServiceException SFORCESERVICE_EXCEPTION;
    private final static QName SFORCESERVICE_QNAME = new QName("urn:partner.soap.sforce.com", "SforceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/dev-workspace/ToolingAPI/apex-analyser/src/main/java/sf_cn_partner.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SFORCESERVICE_WSDL_LOCATION = url;
        SFORCESERVICE_EXCEPTION = e;
    }

    public SforceService() {
        super(__getWsdlLocation(), SFORCESERVICE_QNAME);
    }

    public SforceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SFORCESERVICE_QNAME, features);
    }

    public SforceService(URL wsdlLocation) {
        super(wsdlLocation, SFORCESERVICE_QNAME);
    }

    public SforceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SFORCESERVICE_QNAME, features);
    }

    public SforceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SforceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Soap
     */
    @WebEndpoint(name = "Soap")
    public Soap getSoap() {
        return super.getPort(new QName("urn:partner.soap.sforce.com", "Soap"), Soap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Soap
     */
    @WebEndpoint(name = "Soap")
    public Soap getSoap(WebServiceFeature... features) {
        return super.getPort(new QName("urn:partner.soap.sforce.com", "Soap"), Soap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SFORCESERVICE_EXCEPTION!= null) {
            throw SFORCESERVICE_EXCEPTION;
        }
        return SFORCESERVICE_WSDL_LOCATION;
    }

}
