
package com.nttdata.sf.partner;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Soap", targetNamespace = "urn:partner.soap.sforce.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Soap {


    /**
     * Login to the Salesforce.com SOAP Api
     * 
     * @param username
     * @param password
     * @return
     *     returns com.nttdata.sf.partner.LoginResult
     * @throws LoginFault_Exception
     * @throws UnexpectedErrorFault_Exception
     * @throws InvalidIdFault_Exception
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    @RequestWrapper(localName = "login", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.LoginResponse")
    public LoginResult login(
        @WebParam(name = "username", targetNamespace = "urn:partner.soap.sforce.com")
        String username,
        @WebParam(name = "password", targetNamespace = "urn:partner.soap.sforce.com")
        String password)
        throws InvalidIdFault_Exception, LoginFault_Exception, UnexpectedErrorFault_Exception
    ;

    /**
     * Describe an sObject
     * 
     * @param sObjectType
     * @return
     *     returns com.nttdata.sf.partner.DescribeSObjectResult
     * @throws InvalidSObjectFault_Exception
     * @throws UnexpectedErrorFault_Exception
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    @RequestWrapper(localName = "describeSObject", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.DescribeSObject")
    @ResponseWrapper(localName = "describeSObjectResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.DescribeSObjectResponse")
    public DescribeSObjectResult describeSObject(
        @WebParam(name = "sObjectType", targetNamespace = "urn:partner.soap.sforce.com")
        String sObjectType)
        throws InvalidSObjectFault_Exception, UnexpectedErrorFault_Exception
    ;

    /**
     * Describe a number sObjects
     * 
     * @param sObjectType
     * @return
     *     returns java.util.List<com.nttdata.sf.partner.DescribeSObjectResult>
     * @throws InvalidSObjectFault_Exception
     * @throws UnexpectedErrorFault_Exception
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    @RequestWrapper(localName = "describeSObjects", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.DescribeSObjects")
    @ResponseWrapper(localName = "describeSObjectsResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.DescribeSObjectsResponse")
    public List<DescribeSObjectResult> describeSObjects(
        @WebParam(name = "sObjectType", targetNamespace = "urn:partner.soap.sforce.com")
        List<String> sObjectType)
        throws InvalidSObjectFault_Exception, UnexpectedErrorFault_Exception
    ;

    /**
     * Describe the Global state
     * 
     * @return
     *     returns com.nttdata.sf.partner.DescribeGlobalResult
     * @throws UnexpectedErrorFault_Exception
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    @RequestWrapper(localName = "describeGlobal", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.DescribeGlobal")
    @ResponseWrapper(localName = "describeGlobalResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.DescribeGlobalResponse")
    public DescribeGlobalResult describeGlobal()
        throws UnexpectedErrorFault_Exception
    ;

    /**
     * Describe all the data category groups available for a given set of types
     * 
     * @param sObjectType
     * @return
     *     returns java.util.List<com.nttdata.sf.partner.DescribeDataCategoryGroupResult>
     * @throws InvalidSObjectFault_Exception
     * @throws UnexpectedErrorFault_Exception
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    @RequestWrapper(localName = "describeDataCategoryGroups", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.DescribeDataCategoryGroups")
    @ResponseWrapper(localName = "describeDataCategoryGroupsResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.DescribeDataCategoryGroupsResponse")
    public List<DescribeDataCategoryGroupResult> describeDataCategoryGroups(
        @WebParam(name = "sObjectType", targetNamespace = "urn:partner.soap.sforce.com")
        List<String> sObjectType)
        throws InvalidSObjectFault_Exception, UnexpectedErrorFault_Exception
    ;

    /**
     * Describe the data category group structures for a given set of pair of types and data category group name
     * 
     * @param pairs
     * @param topCategoriesOnly
     * @return
     *     returns java.util.List<com.nttdata.sf.partner.DescribeDataCategoryGroupStructureResult>
     * @throws InvalidSObjectFault_Exception
     * @throws UnexpectedErrorFault_Exception
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    @RequestWrapper(localName = "describeDataCategoryGroupStructures", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.DescribeDataCategoryGroupStructures")
    @ResponseWrapper(localName = "describeDataCategoryGroupStructuresResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.DescribeDataCategoryGroupStructuresResponse")
    public List<DescribeDataCategoryGroupStructureResult> describeDataCategoryGroupStructures(
        @WebParam(name = "pairs", targetNamespace = "urn:partner.soap.sforce.com")
        List<DataCategoryGroupSobjectTypePair> pairs,
        @WebParam(name = "topCategoriesOnly", targetNamespace = "urn:partner.soap.sforce.com")
        boolean topCategoriesOnly)
        throws InvalidSObjectFault_Exception, UnexpectedErrorFault_Exception
    ;

    /**
     * Describes your Knowledge settings, such as if knowledgeEnabled is on or off, its default language and supported languages
     * 
     * @return
     *     returns com.nttdata.sf.partner.KnowledgeSettings
     * @throws UnexpectedErrorFault_Exception
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    @RequestWrapper(localName = "describeKnowledgeSettings", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.DescribeKnowledgeSettings")
    @ResponseWrapper(localName = "describeKnowledgeSettingsResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.DescribeKnowledgeSettingsResponse")
    public KnowledgeSettings describeKnowledgeSettings()
        throws UnexpectedErrorFault_Exception
    ;

    /**
     * Describe a list of FlexiPage and their contents
     * 
     * @param flexiPages
     * @return
     *     returns java.util.List<com.nttdata.sf.partner.DescribeFlexiPageResult>
     * @throws UnexpectedErrorFault_Exception
     * @throws InvalidIdFault_Exception
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    @RequestWrapper(localName = "describeFlexiPages", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.DescribeFlexiPages")
    @ResponseWrapper(localName = "describeFlexiPagesResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.DescribeFlexiPagesResponse")
    public List<DescribeFlexiPageResult> describeFlexiPages(
        @WebParam(name = "flexiPages", targetNamespace = "urn:partner.soap.sforce.com")
        List<String> flexiPages)
        throws InvalidIdFault_Exception, UnexpectedErrorFault_Exception
    ;

    /**
     * Describe the items in an AppMenu
     * 
     * @param appMenuType
     * @return
     *     returns com.nttdata.sf.partner.DescribeAppMenuResult
     * @throws UnexpectedErrorFault_Exception
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    @RequestWrapper(localName = "describeAppMenu", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.DescribeAppMenu")
    @ResponseWrapper(localName = "describeAppMenuResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.DescribeAppMenuResponse")
    public DescribeAppMenuResult describeAppMenu(
        @WebParam(name = "appMenuType", targetNamespace = "urn:partner.soap.sforce.com")
        AppMenuType appMenuType)
        throws UnexpectedErrorFault_Exception
    ;

    /**
     * Describe Gloal and Themes
     * 
     * @return
     *     returns com.nttdata.sf.partner.DescribeGlobalTheme2
     * @throws UnexpectedErrorFault_Exception
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    @RequestWrapper(localName = "describeGlobalTheme", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.DescribeGlobalTheme")
    @ResponseWrapper(localName = "describeGlobalThemeResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.DescribeGlobalThemeResponse")
    public DescribeGlobalTheme2 describeGlobalTheme()
        throws UnexpectedErrorFault_Exception
    ;

    /**
     * Describe Themes
     * 
     * @param sobjectType
     * @return
     *     returns com.nttdata.sf.partner.DescribeThemeResult
     * @throws UnexpectedErrorFault_Exception
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    @RequestWrapper(localName = "describeTheme", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.DescribeTheme")
    @ResponseWrapper(localName = "describeThemeResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.DescribeThemeResponse")
    public DescribeThemeResult describeTheme(
        @WebParam(name = "sobjectType", targetNamespace = "urn:partner.soap.sforce.com")
        List<String> sobjectType)
        throws UnexpectedErrorFault_Exception
    ;

    /**
     * Describe the layout of the given sObject or the given actionable global page.
     * 
     * @param recordTypeIds
     * @param sObjectType
     * @param layoutName
     * @return
     *     returns com.nttdata.sf.partner.DescribeLayoutResult
     * @throws InvalidSObjectFault_Exception
     * @throws UnexpectedErrorFault_Exception
     * @throws InvalidIdFault_Exception
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    @RequestWrapper(localName = "describeLayout", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.DescribeLayout")
    @ResponseWrapper(localName = "describeLayoutResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.DescribeLayoutResponse")
    public DescribeLayoutResult describeLayout(
        @WebParam(name = "sObjectType", targetNamespace = "urn:partner.soap.sforce.com")
        String sObjectType,
        @WebParam(name = "layoutName", targetNamespace = "urn:partner.soap.sforce.com")
        String layoutName,
        @WebParam(name = "recordTypeIds", targetNamespace = "urn:partner.soap.sforce.com")
        List<String> recordTypeIds)
        throws InvalidIdFault_Exception, InvalidSObjectFault_Exception, UnexpectedErrorFault_Exception
    ;

    /**
     * Describe the layout of the SoftPhone
     * 
     * @return
     *     returns com.nttdata.sf.partner.DescribeSoftphoneLayoutResult
     * @throws UnexpectedErrorFault_Exception
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    @RequestWrapper(localName = "describeSoftphoneLayout", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.DescribeSoftphoneLayout")
    @ResponseWrapper(localName = "describeSoftphoneLayoutResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.DescribeSoftphoneLayoutResponse")
    public DescribeSoftphoneLayoutResult describeSoftphoneLayout()
        throws UnexpectedErrorFault_Exception
    ;

    /**
     * Describe the search view of an sObject
     * 
     * @param sObjectType
     * @return
     *     returns java.util.List<com.nttdata.sf.partner.DescribeSearchLayoutResult>
     * @throws InvalidSObjectFault_Exception
     * @throws UnexpectedErrorFault_Exception
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    @RequestWrapper(localName = "describeSearchLayouts", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.DescribeSearchLayouts")
    @ResponseWrapper(localName = "describeSearchLayoutsResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.DescribeSearchLayoutsResponse")
    public List<DescribeSearchLayoutResult> describeSearchLayouts(
        @WebParam(name = "sObjectType", targetNamespace = "urn:partner.soap.sforce.com")
        List<String> sObjectType)
        throws InvalidSObjectFault_Exception, UnexpectedErrorFault_Exception
    ;

    /**
     * Describe a list of objects representing the order and scope of objects on a users search result page
     * 
     * @return
     *     returns java.util.List<com.nttdata.sf.partner.DescribeSearchScopeOrderResult>
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    @RequestWrapper(localName = "describeSearchScopeOrder", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.DescribeSearchScopeOrder")
    @ResponseWrapper(localName = "describeSearchScopeOrderResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.DescribeSearchScopeOrderResponse")
    public List<DescribeSearchScopeOrderResult> describeSearchScopeOrder();

    /**
     * Describe the compact layouts of the given sObject
     * 
     * @param recordTypeIds
     * @param sObjectType
     * @return
     *     returns com.nttdata.sf.partner.DescribeCompactLayoutsResult
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    @RequestWrapper(localName = "describeCompactLayouts", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.DescribeCompactLayouts")
    @ResponseWrapper(localName = "describeCompactLayoutsResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.DescribeCompactLayoutsResponse")
    public DescribeCompactLayoutsResult describeCompactLayouts(
        @WebParam(name = "sObjectType", targetNamespace = "urn:partner.soap.sforce.com")
        String sObjectType,
        @WebParam(name = "recordTypeIds", targetNamespace = "urn:partner.soap.sforce.com")
        List<String> recordTypeIds);

    /**
     * Describe the approval layouts of the given sObject
     * 
     * @param sObjectType
     * @param approvalProcessNames
     * @return
     *     returns com.nttdata.sf.partner.DescribeApprovalLayoutResult
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    @RequestWrapper(localName = "describeApprovalLayout", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.DescribeApprovalLayout")
    @ResponseWrapper(localName = "describeApprovalLayoutResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.DescribeApprovalLayoutResponse")
    public DescribeApprovalLayoutResult describeApprovalLayout(
        @WebParam(name = "sObjectType", targetNamespace = "urn:partner.soap.sforce.com")
        String sObjectType,
        @WebParam(name = "approvalProcessNames", targetNamespace = "urn:partner.soap.sforce.com")
        List<String> approvalProcessNames);

    /**
     * Describe the ListViews as SOQL metadata for the generation of SOQL.
     * 
     * @param request
     * @return
     *     returns com.nttdata.sf.partner.DescribeSoqlListViewResult
     * @throws InvalidSObjectFault_Exception
     * @throws UnexpectedErrorFault_Exception
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    @RequestWrapper(localName = "describeSoqlListViews", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.DescribeSoqlListViews")
    @ResponseWrapper(localName = "describeSoqlListViewsResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.DescribeSoqlListViewsResponse")
    public DescribeSoqlListViewResult describeSoqlListViews(
        @WebParam(name = "request", targetNamespace = "urn:partner.soap.sforce.com")
        DescribeSoqlListViewsRequest request)
        throws InvalidSObjectFault_Exception, UnexpectedErrorFault_Exception
    ;

    /**
     * Execute the specified list view and return the presentation-ready results.
     * 
     * @param request
     * @return
     *     returns com.nttdata.sf.partner.ExecuteListViewResult
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    @RequestWrapper(localName = "executeListView", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.ExecuteListView")
    @ResponseWrapper(localName = "executeListViewResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.ExecuteListViewResponse")
    public ExecuteListViewResult executeListView(
        @WebParam(name = "request", targetNamespace = "urn:partner.soap.sforce.com")
        ExecuteListViewRequest request);

    /**
     * Describe the tabs that appear on a users page
     * 
     * @return
     *     returns java.util.List<com.nttdata.sf.partner.DescribeTabSetResult>
     * @throws UnexpectedErrorFault_Exception
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    @RequestWrapper(localName = "describeTabs", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.DescribeTabs")
    @ResponseWrapper(localName = "describeTabsResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.DescribeTabsResponse")
    public List<DescribeTabSetResult> describeTabs()
        throws UnexpectedErrorFault_Exception
    ;

    /**
     * Describe all tabs available to a user
     * 
     * @return
     *     returns java.util.List<com.nttdata.sf.partner.DescribeTab>
     * @throws UnexpectedErrorFault_Exception
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    @RequestWrapper(localName = "describeAllTabs", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.DescribeAllTabs")
    @ResponseWrapper(localName = "describeAllTabsResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.DescribeAllTabsResponse")
    public List<DescribeTab> describeAllTabs()
        throws UnexpectedErrorFault_Exception
    ;

    /**
     * Describe the primary compact layouts for the sObjects requested
     * 
     * @param sObjectTypes
     * @return
     *     returns java.util.List<com.nttdata.sf.partner.DescribeCompactLayout>
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    @RequestWrapper(localName = "describePrimaryCompactLayouts", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.DescribePrimaryCompactLayouts")
    @ResponseWrapper(localName = "describePrimaryCompactLayoutsResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.DescribePrimaryCompactLayoutsResponse")
    public List<DescribeCompactLayout> describePrimaryCompactLayouts(
        @WebParam(name = "sObjectTypes", targetNamespace = "urn:partner.soap.sforce.com")
        List<String> sObjectTypes);

    /**
     * Create a set of new sObjects
     * 
     * @param sObjects
     * @return
     *     returns java.util.List<com.nttdata.sf.partner.SaveResult>
     * @throws InvalidFieldFault_Exception
     * @throws InvalidSObjectFault_Exception
     * @throws UnexpectedErrorFault_Exception
     * @throws InvalidIdFault_Exception
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    @RequestWrapper(localName = "create", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.Create")
    @ResponseWrapper(localName = "createResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.CreateResponse")
    public List<SaveResult> create(
        @WebParam(name = "sObjects", targetNamespace = "urn:partner.soap.sforce.com")
        List<SObject> sObjects)
        throws InvalidFieldFault_Exception, InvalidIdFault_Exception, InvalidSObjectFault_Exception, UnexpectedErrorFault_Exception
    ;

    /**
     * Update a set of sObjects
     * 
     * @param sObjects
     * @return
     *     returns java.util.List<com.nttdata.sf.partner.SaveResult>
     * @throws InvalidFieldFault_Exception
     * @throws InvalidSObjectFault_Exception
     * @throws UnexpectedErrorFault_Exception
     * @throws InvalidIdFault_Exception
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    @RequestWrapper(localName = "update", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.UpdateResponse")
    public List<SaveResult> update(
        @WebParam(name = "sObjects", targetNamespace = "urn:partner.soap.sforce.com")
        List<SObject> sObjects)
        throws InvalidFieldFault_Exception, InvalidIdFault_Exception, InvalidSObjectFault_Exception, UnexpectedErrorFault_Exception
    ;

    /**
     * Update or insert a set of sObjects based on object id
     * 
     * @param externalIDFieldName
     * @param sObjects
     * @return
     *     returns java.util.List<com.nttdata.sf.partner.UpsertResult>
     * @throws InvalidFieldFault_Exception
     * @throws InvalidSObjectFault_Exception
     * @throws UnexpectedErrorFault_Exception
     * @throws InvalidIdFault_Exception
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    @RequestWrapper(localName = "upsert", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.Upsert")
    @ResponseWrapper(localName = "upsertResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.UpsertResponse")
    public List<UpsertResult> upsert(
        @WebParam(name = "externalIDFieldName", targetNamespace = "urn:partner.soap.sforce.com")
        String externalIDFieldName,
        @WebParam(name = "sObjects", targetNamespace = "urn:partner.soap.sforce.com")
        List<SObject> sObjects)
        throws InvalidFieldFault_Exception, InvalidIdFault_Exception, InvalidSObjectFault_Exception, UnexpectedErrorFault_Exception
    ;

    /**
     * Merge and update a set of sObjects based on object id
     * 
     * @param request
     * @return
     *     returns java.util.List<com.nttdata.sf.partner.MergeResult>
     * @throws InvalidSObjectFault_Exception
     * @throws InvalidFieldFault_Exception
     * @throws UnexpectedErrorFault_Exception
     * @throws InvalidIdFault_Exception
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    @RequestWrapper(localName = "merge", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.Merge")
    @ResponseWrapper(localName = "mergeResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.MergeResponse")
    public List<MergeResult> merge(
        @WebParam(name = "request", targetNamespace = "urn:partner.soap.sforce.com")
        List<MergeRequest> request)
        throws InvalidFieldFault_Exception, InvalidIdFault_Exception, InvalidSObjectFault_Exception, UnexpectedErrorFault_Exception
    ;

    /**
     * Delete a set of sObjects
     * 
     * @param ids
     * @return
     *     returns java.util.List<com.nttdata.sf.partner.DeleteResult>
     * @throws UnexpectedErrorFault_Exception
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    @RequestWrapper(localName = "delete", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.DeleteResponse")
    public List<DeleteResult> delete(
        @WebParam(name = "ids", targetNamespace = "urn:partner.soap.sforce.com")
        List<String> ids)
        throws UnexpectedErrorFault_Exception
    ;

    /**
     * Undelete a set of sObjects
     * 
     * @param ids
     * @return
     *     returns java.util.List<com.nttdata.sf.partner.UndeleteResult>
     * @throws UnexpectedErrorFault_Exception
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    @RequestWrapper(localName = "undelete", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.Undelete")
    @ResponseWrapper(localName = "undeleteResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.UndeleteResponse")
    public List<UndeleteResult> undelete(
        @WebParam(name = "ids", targetNamespace = "urn:partner.soap.sforce.com")
        List<String> ids)
        throws UnexpectedErrorFault_Exception
    ;

    /**
     * Empty a set of sObjects from the recycle bin
     * 
     * @param ids
     * @return
     *     returns java.util.List<com.nttdata.sf.partner.EmptyRecycleBinResult>
     * @throws UnexpectedErrorFault_Exception
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    @RequestWrapper(localName = "emptyRecycleBin", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.EmptyRecycleBin")
    @ResponseWrapper(localName = "emptyRecycleBinResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.EmptyRecycleBinResponse")
    public List<EmptyRecycleBinResult> emptyRecycleBin(
        @WebParam(name = "ids", targetNamespace = "urn:partner.soap.sforce.com")
        List<String> ids)
        throws UnexpectedErrorFault_Exception
    ;

    /**
     * Get a set of sObjects
     * 
     * @param fieldList
     * @param sObjectType
     * @param ids
     * @return
     *     returns java.util.List<com.nttdata.sf.partner.SObject>
     * @throws InvalidSObjectFault_Exception
     * @throws InvalidFieldFault_Exception
     * @throws UnexpectedErrorFault_Exception
     * @throws MalformedQueryFault_Exception
     * @throws InvalidIdFault_Exception
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    @RequestWrapper(localName = "retrieve", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.Retrieve")
    @ResponseWrapper(localName = "retrieveResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.RetrieveResponse")
    public List<SObject> retrieve(
        @WebParam(name = "fieldList", targetNamespace = "urn:partner.soap.sforce.com")
        String fieldList,
        @WebParam(name = "sObjectType", targetNamespace = "urn:partner.soap.sforce.com")
        String sObjectType,
        @WebParam(name = "ids", targetNamespace = "urn:partner.soap.sforce.com")
        List<String> ids)
        throws InvalidFieldFault_Exception, InvalidIdFault_Exception, InvalidSObjectFault_Exception, MalformedQueryFault_Exception, UnexpectedErrorFault_Exception
    ;

    /**
     * Submit an entity to a workflow process or process a workitem
     * 
     * @param actions
     * @return
     *     returns java.util.List<com.nttdata.sf.partner.ProcessResult>
     * @throws UnexpectedErrorFault_Exception
     * @throws InvalidIdFault_Exception
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    @RequestWrapper(localName = "process", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.Process")
    @ResponseWrapper(localName = "processResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.ProcessResponse")
    public List<ProcessResult> process(
        @WebParam(name = "actions", targetNamespace = "urn:partner.soap.sforce.com")
        List<ProcessRequest> actions)
        throws InvalidIdFault_Exception, UnexpectedErrorFault_Exception
    ;

    /**
     * convert a set of leads
     * 
     * @param leadConverts
     * @return
     *     returns java.util.List<com.nttdata.sf.partner.LeadConvertResult>
     * @throws UnexpectedErrorFault_Exception
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    @RequestWrapper(localName = "convertLead", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.ConvertLead")
    @ResponseWrapper(localName = "convertLeadResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.ConvertLeadResponse")
    public List<LeadConvertResult> convertLead(
        @WebParam(name = "leadConverts", targetNamespace = "urn:partner.soap.sforce.com")
        List<LeadConvert> leadConverts)
        throws UnexpectedErrorFault_Exception
    ;

    /**
     * Logout the current user, invalidating the current session.
     * 
     * @throws UnexpectedErrorFault_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "logout", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.Logout")
    @ResponseWrapper(localName = "logoutResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.LogoutResponse")
    public void logout()
        throws UnexpectedErrorFault_Exception
    ;

    /**
     * Logs out and invalidates session ids
     * 
     * @param sessionIds
     * @return
     *     returns java.util.List<com.nttdata.sf.partner.InvalidateSessionsResult>
     * @throws UnexpectedErrorFault_Exception
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    @RequestWrapper(localName = "invalidateSessions", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.InvalidateSessions")
    @ResponseWrapper(localName = "invalidateSessionsResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.InvalidateSessionsResponse")
    public List<InvalidateSessionsResult> invalidateSessions(
        @WebParam(name = "sessionIds", targetNamespace = "urn:partner.soap.sforce.com")
        List<String> sessionIds)
        throws UnexpectedErrorFault_Exception
    ;

    /**
     * Get the IDs for deleted sObjects
     * 
     * @param startDate
     * @param sObjectType
     * @param endDate
     * @return
     *     returns com.nttdata.sf.partner.GetDeletedResult
     * @throws InvalidSObjectFault_Exception
     * @throws UnexpectedErrorFault_Exception
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    @RequestWrapper(localName = "getDeleted", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.GetDeleted")
    @ResponseWrapper(localName = "getDeletedResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.GetDeletedResponse")
    public GetDeletedResult getDeleted(
        @WebParam(name = "sObjectType", targetNamespace = "urn:partner.soap.sforce.com")
        String sObjectType,
        @WebParam(name = "startDate", targetNamespace = "urn:partner.soap.sforce.com")
        XMLGregorianCalendar startDate,
        @WebParam(name = "endDate", targetNamespace = "urn:partner.soap.sforce.com")
        XMLGregorianCalendar endDate)
        throws InvalidSObjectFault_Exception, UnexpectedErrorFault_Exception
    ;

    /**
     * Get the IDs for updated sObjects
     * 
     * @param startDate
     * @param sObjectType
     * @param endDate
     * @return
     *     returns com.nttdata.sf.partner.GetUpdatedResult
     * @throws InvalidSObjectFault_Exception
     * @throws UnexpectedErrorFault_Exception
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    @RequestWrapper(localName = "getUpdated", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.GetUpdated")
    @ResponseWrapper(localName = "getUpdatedResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.GetUpdatedResponse")
    public GetUpdatedResult getUpdated(
        @WebParam(name = "sObjectType", targetNamespace = "urn:partner.soap.sforce.com")
        String sObjectType,
        @WebParam(name = "startDate", targetNamespace = "urn:partner.soap.sforce.com")
        XMLGregorianCalendar startDate,
        @WebParam(name = "endDate", targetNamespace = "urn:partner.soap.sforce.com")
        XMLGregorianCalendar endDate)
        throws InvalidSObjectFault_Exception, UnexpectedErrorFault_Exception
    ;

    /**
     * Create a Query Cursor
     * 
     * @param queryString
     * @return
     *     returns com.nttdata.sf.partner.QueryResult
     * @throws InvalidFieldFault_Exception
     * @throws InvalidSObjectFault_Exception
     * @throws InvalidQueryLocatorFault_Exception
     * @throws UnexpectedErrorFault_Exception
     * @throws MalformedQueryFault_Exception
     * @throws InvalidIdFault_Exception
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    @RequestWrapper(localName = "query", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.Query")
    @ResponseWrapper(localName = "queryResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.QueryResponse")
    public QueryResult query(
        @WebParam(name = "queryString", targetNamespace = "urn:partner.soap.sforce.com")
        String queryString)
        throws InvalidFieldFault_Exception, InvalidIdFault_Exception, InvalidQueryLocatorFault_Exception, InvalidSObjectFault_Exception, MalformedQueryFault_Exception, UnexpectedErrorFault_Exception
    ;

    /**
     * Create a Query Cursor, including deleted sObjects
     * 
     * @param queryString
     * @return
     *     returns com.nttdata.sf.partner.QueryResult
     * @throws InvalidSObjectFault_Exception
     * @throws InvalidFieldFault_Exception
     * @throws InvalidQueryLocatorFault_Exception
     * @throws UnexpectedErrorFault_Exception
     * @throws MalformedQueryFault_Exception
     * @throws InvalidIdFault_Exception
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    @RequestWrapper(localName = "queryAll", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.QueryAll")
    @ResponseWrapper(localName = "queryAllResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.QueryAllResponse")
    public QueryResult queryAll(
        @WebParam(name = "queryString", targetNamespace = "urn:partner.soap.sforce.com")
        String queryString)
        throws InvalidFieldFault_Exception, InvalidIdFault_Exception, InvalidQueryLocatorFault_Exception, InvalidSObjectFault_Exception, MalformedQueryFault_Exception, UnexpectedErrorFault_Exception
    ;

    /**
     * Gets the next batch of sObjects from a query
     * 
     * @param queryLocator
     * @return
     *     returns com.nttdata.sf.partner.QueryResult
     * @throws InvalidFieldFault_Exception
     * @throws InvalidQueryLocatorFault_Exception
     * @throws UnexpectedErrorFault_Exception
     * @throws MalformedQueryFault_Exception
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    @RequestWrapper(localName = "queryMore", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.QueryMore")
    @ResponseWrapper(localName = "queryMoreResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.QueryMoreResponse")
    public QueryResult queryMore(
        @WebParam(name = "queryLocator", targetNamespace = "urn:partner.soap.sforce.com")
        String queryLocator)
        throws InvalidFieldFault_Exception, InvalidQueryLocatorFault_Exception, MalformedQueryFault_Exception, UnexpectedErrorFault_Exception
    ;

    /**
     * Search for sObjects
     * 
     * @param searchString
     * @return
     *     returns com.nttdata.sf.partner.SearchResult
     * @throws InvalidFieldFault_Exception
     * @throws InvalidSObjectFault_Exception
     * @throws MalformedSearchFault_Exception
     * @throws UnexpectedErrorFault_Exception
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    @RequestWrapper(localName = "search", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.Search")
    @ResponseWrapper(localName = "searchResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.SearchResponse")
    public SearchResult search(
        @WebParam(name = "searchString", targetNamespace = "urn:partner.soap.sforce.com")
        String searchString)
        throws InvalidFieldFault_Exception, InvalidSObjectFault_Exception, MalformedSearchFault_Exception, UnexpectedErrorFault_Exception
    ;

    /**
     * Gets server timestamp
     * 
     * @return
     *     returns com.nttdata.sf.partner.GetServerTimestampResult
     * @throws UnexpectedErrorFault_Exception
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    @RequestWrapper(localName = "getServerTimestamp", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.GetServerTimestamp")
    @ResponseWrapper(localName = "getServerTimestampResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.GetServerTimestampResponse")
    public GetServerTimestampResult getServerTimestamp()
        throws UnexpectedErrorFault_Exception
    ;

    /**
     * Set a user's password
     * 
     * @param userId
     * @param password
     * @return
     *     returns com.nttdata.sf.partner.SetPasswordResult
     * @throws InvalidNewPasswordFault_Exception
     * @throws UnexpectedErrorFault_Exception
     * @throws InvalidIdFault_Exception
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    @RequestWrapper(localName = "setPassword", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.SetPassword")
    @ResponseWrapper(localName = "setPasswordResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.SetPasswordResponse")
    public SetPasswordResult setPassword(
        @WebParam(name = "userId", targetNamespace = "urn:partner.soap.sforce.com")
        String userId,
        @WebParam(name = "password", targetNamespace = "urn:partner.soap.sforce.com")
        String password)
        throws InvalidIdFault_Exception, InvalidNewPasswordFault_Exception, UnexpectedErrorFault_Exception
    ;

    /**
     * Reset a user's password
     * 
     * @param userId
     * @return
     *     returns com.nttdata.sf.partner.ResetPasswordResult
     * @throws UnexpectedErrorFault_Exception
     * @throws InvalidIdFault_Exception
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    @RequestWrapper(localName = "resetPassword", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.ResetPassword")
    @ResponseWrapper(localName = "resetPasswordResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.ResetPasswordResponse")
    public ResetPasswordResult resetPassword(
        @WebParam(name = "userId", targetNamespace = "urn:partner.soap.sforce.com")
        String userId)
        throws InvalidIdFault_Exception, UnexpectedErrorFault_Exception
    ;

    /**
     * Returns standard information relevant to the current user
     * 
     * @return
     *     returns com.nttdata.sf.partner.GetUserInfoResult
     * @throws UnexpectedErrorFault_Exception
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    @RequestWrapper(localName = "getUserInfo", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.GetUserInfo")
    @ResponseWrapper(localName = "getUserInfoResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.GetUserInfoResponse")
    public GetUserInfoResult getUserInfo()
        throws UnexpectedErrorFault_Exception
    ;

    /**
     * Send existing draft EmailMessage
     * 
     * @param ids
     * @return
     *     returns java.util.List<com.nttdata.sf.partner.SendEmailResult>
     * @throws UnexpectedErrorFault_Exception
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    @RequestWrapper(localName = "sendEmailMessage", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.SendEmailMessage")
    @ResponseWrapper(localName = "sendEmailMessageResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.SendEmailMessageResponse")
    public List<SendEmailResult> sendEmailMessage(
        @WebParam(name = "ids", targetNamespace = "urn:partner.soap.sforce.com")
        List<String> ids)
        throws UnexpectedErrorFault_Exception
    ;

    /**
     * Send outbound email
     * 
     * @param messages
     * @return
     *     returns java.util.List<com.nttdata.sf.partner.SendEmailResult>
     * @throws UnexpectedErrorFault_Exception
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    @RequestWrapper(localName = "sendEmail", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.SendEmail")
    @ResponseWrapper(localName = "sendEmailResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.SendEmailResponse")
    public List<SendEmailResult> sendEmail(
        @WebParam(name = "messages", targetNamespace = "urn:partner.soap.sforce.com")
        List<Email> messages)
        throws UnexpectedErrorFault_Exception
    ;

    /**
     * Perform a series of predefined actions such as quick create or log a task
     * 
     * @param quickActions
     * @return
     *     returns java.util.List<com.nttdata.sf.partner.PerformQuickActionResult>
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    @RequestWrapper(localName = "performQuickActions", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.PerformQuickActions")
    @ResponseWrapper(localName = "performQuickActionsResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.PerformQuickActionsResponse")
    public List<PerformQuickActionResult> performQuickActions(
        @WebParam(name = "quickActions", targetNamespace = "urn:partner.soap.sforce.com")
        List<PerformQuickActionRequest> quickActions);

    /**
     * Describe the details of a series of quick actions
     * 
     * @param quickActions
     * @return
     *     returns java.util.List<com.nttdata.sf.partner.DescribeQuickActionResult>
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    @RequestWrapper(localName = "describeQuickActions", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.DescribeQuickActions")
    @ResponseWrapper(localName = "describeQuickActionsResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.DescribeQuickActionsResponse")
    public List<DescribeQuickActionResult> describeQuickActions(
        @WebParam(name = "quickActions", targetNamespace = "urn:partner.soap.sforce.com")
        List<String> quickActions);

    /**
     * Describe the details of a series of quick actions available for the given contextType
     * 
     * @param contextType
     * @return
     *     returns java.util.List<com.nttdata.sf.partner.DescribeAvailableQuickActionResult>
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    @RequestWrapper(localName = "describeAvailableQuickActions", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.DescribeAvailableQuickActions")
    @ResponseWrapper(localName = "describeAvailableQuickActionsResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.DescribeAvailableQuickActionsResponse")
    public List<DescribeAvailableQuickActionResult> describeAvailableQuickActions(
        @WebParam(name = "contextType", targetNamespace = "urn:partner.soap.sforce.com")
        String contextType);

    /**
     * Retreive the template sobjects, if appropriate, for the given quick action names in a given context
     * 
     * @param contextId
     * @param quickActionNames
     * @return
     *     returns java.util.List<com.nttdata.sf.partner.QuickActionTemplateResult>
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "urn:partner.soap.sforce.com")
    @RequestWrapper(localName = "retrieveQuickActionTemplates", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.RetrieveQuickActionTemplates")
    @ResponseWrapper(localName = "retrieveQuickActionTemplatesResponse", targetNamespace = "urn:partner.soap.sforce.com", className = "com.nttdata.sf.partner.RetrieveQuickActionTemplatesResponse")
    public List<QuickActionTemplateResult> retrieveQuickActionTemplates(
        @WebParam(name = "quickActionNames", targetNamespace = "urn:partner.soap.sforce.com")
        List<String> quickActionNames,
        @WebParam(name = "contextId", targetNamespace = "urn:partner.soap.sforce.com")
        String contextId);

}
